#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="$ROOT_DIR/native/build"

WEBRTC_ROOT="${WEBRTC_ROOT:-}"
WEBRTC_INCLUDE_DIR="${WEBRTC_INCLUDE_DIR:-}"
WEBRTC_LIB_DIR="${WEBRTC_LIB_DIR:-}"
WEBRTC_LIBS="${WEBRTC_LIBS:-}"
ONNXRUNTIME_ROOT="${ONNXRUNTIME_ROOT:-}"
ONNXRUNTIME_INCLUDE_DIR="${ONNXRUNTIME_INCLUDE_DIR:-}"
ONNXRUNTIME_LIB_DIR="${ONNXRUNTIME_LIB_DIR:-}"
ONNXRUNTIME_LIBS="${ONNXRUNTIME_LIBS:-}"

cmake -S "$ROOT_DIR/native" -B "$BUILD_DIR" \
  -DCMAKE_BUILD_TYPE=Release \
  -DWEBRTC_ROOT="$WEBRTC_ROOT" \
  -DWEBRTC_INCLUDE_DIR="$WEBRTC_INCLUDE_DIR" \
  -DWEBRTC_LIB_DIR="$WEBRTC_LIB_DIR" \
  -DWEBRTC_LIBS="$WEBRTC_LIBS" \
  -DONNXRUNTIME_ROOT="$ONNXRUNTIME_ROOT" \
  -DONNXRUNTIME_INCLUDE_DIR="$ONNXRUNTIME_INCLUDE_DIR" \
  -DONNXRUNTIME_LIB_DIR="$ONNXRUNTIME_LIB_DIR" \
  -DONNXRUNTIME_LIBS="$ONNXRUNTIME_LIBS"

cmake --build "$BUILD_DIR" --config Release

echo "Plugins built to: $BUILD_DIR/gst-plugins"
